import { useNavigate } from "react-router-dom";

export function Home() {
    const navigate = useNavigate();
    return (
        <div className="flex flex-col justify-center items-center">
            <h1 className="text-4xl font-bold mb-8 text-center text-gray-800">
                Welcome to Diary AI
            </h1>

            <p className="text-lg text-center max-w-3xl mb-8 text-gray-700">
                Diary AI is your personal diary companion where you can document
                your daily events, thoughts, and feelings. Write about your day
                and receive insightful replies generated by AI. Follow your
                favorite diaries, explore trending topics, and connect with
                like-minded individuals.
            </p>
            <p className="text-lg text-center max-w-3xl m-4 text-gray-700">
                Whether you're looking to organize your thoughts, reflect on
                your day, or simply express yourself, Diary AI provides a safe
                and supportive space for you to do so.
            </p>
            <button
                onClick={() => navigate("/signup")}
                className="bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded shadow"
            >
                Get Started
            </button>
            <p className="text-lg text-center m-4 max-w-3xl text-gray-700">
                Join us today and start your journey towards self-discovery and
                personal growth.
            </p>
            <p className="text-sm text-gray-600 text-center mb-4">
                This is a test environment for demonstration purposes only.
            </p>
        </div>
    );
}
